#include <stdio.h>
#include <string.h>
#include "../include/parser.h"

void parse_log_line(const char *line, LogEntry *entry)
{
    // Initialize entry to safe default values
    memset(entry, 0, sizeof(LogEntry));

    // Try format 1: Exact format generated by tests/generate_test_log.py
    // Example: "2024-01-01T00:00:00.000 WARN 10.0.0.1 "/health" 301 568ms - Retry attempt"
    // Format parses: Timestamp LogLevel IP "Path" StatusCode
    int parsed = sscanf(line, "%31s %7s %45s \"%*[^\"]\" %d",
                        entry->timestamp,
                        entry->log_level,
                        entry->ip_address,
                        &entry->status_code);

    // Try format 2: The example format from the instructions
    // Example: "192.168.1.1 INFO 200 [01/Jun/2026] "GET /home""
    // Format parses: IP LogLevel StatusCode [Timestamp]
    if (parsed < 4) {
        memset(entry, 0, sizeof(LogEntry));
        parsed = sscanf(line, "%45s %7s %d [%31[^]]]",
                        entry->ip_address,
                        entry->log_level,
                        &entry->status_code,
                        entry->timestamp);
    }
}

void accumulate_metrics(const LogEntry *entry, ThreadMetrics *metrics)
{
    metrics->total_lines++;

    // Check log level
    if (strcmp(entry->log_level, "INFO") == 0) {
        metrics->info_count++;
    } else if (strcmp(entry->log_level, "WARN") == 0) {
        metrics->warn_count++;
    } else if (strcmp(entry->log_level, "ERROR") == 0) {
        metrics->error_count++;
    }

    // Check HTTP status code range
    if (entry->status_code >= 200 && entry->status_code < 300) {
        metrics->status_2xx++;
    } else if (entry->status_code >= 400 && entry->status_code < 500) {
        metrics->status_4xx++;
    } else if (entry->status_code >= 500 && entry->status_code < 600) {
        metrics->status_5xx++;
    }
}

void add_ip_to_tracker(IPTracker *tracker, const char *ip)
{
    if (!ip || ip[0] == '\0') return;

    // Linear probe / scan for existing IP
    for (int i = 0; i < tracker->count; i++) {
        if (strcmp(tracker->entries[i].ip_address, ip) == 0) {
            tracker->entries[i].request_count++;
            return;
        }
    }

    // Add as new entry if capacity allows
    if (tracker->count < MAX_IP_TRACK) {
        strncpy(tracker->entries[tracker->count].ip_address, ip, 45);
        tracker->entries[tracker->count].ip_address[45] = '\0';
        tracker->entries[tracker->count].request_count = 1;
        tracker->count++;
    }
}

int detect_anomalies(const IPTracker *tracker, IPCounter *anomalies_out, int max_anomalies, int threshold)
{
    int anomaly_count = 0;
    for (int i = 0; i < tracker->count; i++) {
        if (tracker->entries[i].request_count > threshold) {
            if (anomaly_count < max_anomalies) {
                anomalies_out[anomaly_count] = tracker->entries[i];
                anomaly_count++;
            }
        }
    }
    return anomaly_count;
}
